[package]
name = "mcmmtk"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]

[dependencies]
# TODO: change pw_gix dependency when it goes public
#pw_gix = { git = "https://github.com/pwil3058/rs_pw_gix.git" }
pw_gix = { git = "file:/home/peter/SRC/GITHUB/rs_pw_gix.git" }

gdk = "0.6.0"
gio = "0.2.0"
gtk = "0.2.0"

[features]
default = ["gtk/v3_10"]

